# source = ~/.config/hypr/wallpapers.conf

# Background
background {
    monitor =
    path = ~/Downloads/wallhaven-gwjq3d.jpg
    blur_passes = 3
    blur_size = 2
    noise = 0.04
    contrast = 1
    brightness = 0.5
}

# General
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
}

# Time
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%H")"
  color = rgba(200, 200, 200, 0.75)
  font_size = 100
  font_family = JetBrains Mono Regular
  position = 0, 270
  halign = center
  valign = center
}

label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%M")"
  color = rgba(200, 200, 200, 0.75)
  font_size = 100
  font_family = JetBrains Mono Regular
  position = 0, 160
  halign = center
  valign = center
}

# Date
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(200, 200, 200, 0.75)
  font_size = 20
  font_family = JetBrains Mono
  position = 0, 80
  halign = center
  valign = center
}

# Input field
input-field {
    monitor =
    size = 600, 60
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    font_family = JetBrains Mono SemiBold
    font_color = rgba(200,200,200,0.75)
    fade_on_empty = false
    rounding = -1
    check_color = rgba(0, 0, 0, 0.4)
    fail_color = rgba(0, 0, 0, 0.4)
    fail_text = Wrong password
    placeholder_text = Password
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
}
